name: deploy-docs
run-name: Build and deploy docs
on: [push]
permissions:
  contents: write
jobs:
  deploy-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install mkdocs-material "mkdocstrings[python]>=0.18" \
            digitalhub_runtime_python digitalhub_runtime_container digitalhub_runtime_dbt[local] 
      - run: |
          git fetch --prune --unshallow --tags
          git checkout main
          export VERSIONS=$(echo `git branch -r --format='%(refname:short)'`|sed 's/origin\///g'|sed 's/HEAD//g'|sed 's/main/current/g'|sed 's/gh-pages//g'|xargs|sed 's/ /,/g')
          mkdocs build
      - run: |
          git checkout -b gh-pages
          cp -r site/* .
          rm -r site
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git add --all
          git commit -m "Workflow docs - Current" --allow-empty
          git push -u origin gh-pages
  deploy-versioned:
    needs: deploy-current
    if: github.ref_name != 'main' && github.ref_name != 'gh-pages'
    runs-on: ubuntu-latest
    env:
      DOCS_VERSION: ${{ github.ref_name }}
      USER_STYLESHEETS_PORTAL_SELECTION: ../stylesheets/portal_selection.css
      USER_STYLESHEETS_COLORS: ../stylesheets/colors.css
      DEV_STYLESHEETS_PORTAL_SELECTION: ../../stylesheets/portal_selection.css
      DEV_STYLESHEETS_COLORS: ../../stylesheets/colors.css
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install mkdocs-material digitalhub_runtime_python digitalhub_runtime_container digitalhub_runtime_dbt[local]
      - run: |
          git fetch --prune --unshallow --tags
          git checkout ${{ github.ref_name }}
          export VERSIONS=$(echo `git branch -r --format='%(refname:short)'`|sed 's/origin\///g'|sed 's/HEAD//g'|sed 's/main/current/g'|sed 's/gh-pages//g'|xargs|sed 's/ /,/g')
          mkdocs build
          mv site ${{ github.ref_name }}
      - run: |
          git checkout gh-pages
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git add --all
          git commit -m "Workflow docs - Versioned" --allow-empty
          git push
