name: deploy-docs
run-name: Build and deploy docs
on: [push]
permissions:
  contents: write
jobs:
  deploy-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: |
          git fetch --prune --unshallow --tags
          git checkout main
          export VERSIONS=$(echo `git branch -r --format='%(refname:short)'`|python versions_string.py)
          mkdocs build
      - run: |
          git checkout gh-pages
          cp -r site/* .
          rm -r site
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git add --all
          git commit -m "Workflow docs - Current" --allow-empty
          git push
  deploy-versioned:
    needs: deploy-current
    if: github.ref_name != 'main' && github.ref_name != 'gh-pages'
    runs-on: ubuntu-latest
    env:
      DOCS_VERSION: v:${{ github.ref_name }}
      USER_STYLESHEETS_PORTAL_SELECTION: ../stylesheets/portal_selection.css
      USER_STYLESHEETS_COLORS: ../stylesheets/colors.css
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: |
          git fetch --prune --unshallow --tags
          git checkout ${{ github.ref_name }}
          export VERSIONS=$(echo `git branch -r --format='%(refname:short)'`|python versions_string.py)
          mkdocs build
      - run: |
          git checkout gh-pages
          mkdir -p ${{ github.ref_name }}
          cp -r site/* ${{ github.ref_name }}
          rm -r site
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git add --all
          git commit -m "Workflow docs - Versioned" --allow-empty
          git push
